//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvidencijaPacijenata.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Karton
    {
        public int ID { get; set; }
        [DisplayName("Pacijent")]
        public int IDPacijenta { get; set; }
        [DisplayName("Lekar")]
        public int IDLekara { get; set; }
        [DisplayName("Datum nalaza")]
        public System.DateTime DatumVremeNalaza { get; set; }
        public int Disanje { get; set; }
        public int Puls { get; set; }
        [DisplayName("Telesna temperatura")]
        public double TelesnaTemperatura { get; set; }
        [DisplayName("Krvni pritisak")]
        public string KrvniPritisak { get; set; }
        [DisplayName("Mokraća")]
        public string Mokraca { get; set; }
        public string Stolica { get; set; }
        [DisplayName("Krvna slika")]
        public string KrvaSlika { get; set; }
        [DisplayName("Specifični pregled")]
        public string SpecificniPregled { get; set; }
        [DisplayName("Lekar koji je poslednji menjao rezultate")]
        public virtual Korisnik Korisnik { get; set; }
        [DisplayName("Pacijent")]
        public virtual Korisnik Korisnik1 { get; set; }
    }
}
