//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvidencijaPacijenata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karton
    {
        public int ID { get; set; }
        public int IDPacijenta { get; set; }
        public int IDLekara { get; set; }
        public System.DateTime DatumVremeNalaza { get; set; }
        public int Disanje { get; set; }
        public int Puls { get; set; }
        public double TelesnaTemperatura { get; set; }
        public string KrvniPritisak { get; set; }
        public string Mokraca { get; set; }
        public string Stolica { get; set; }
        public string KrvaSlika { get; set; }
        public string SpecificniPregled { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Korisnik Korisnik1 { get; set; }
    }
}
