//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvidencijaPacijenata.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    public abstract partial class Korisnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Korisnik()
        {
            this.Izvestajs = new HashSet<Izvestaj>();
            this.Izvestajs1 = new HashSet<Izvestaj>();
            this.Kartons = new HashSet<Karton>();
            this.Kartons1 = new HashSet<Karton>();
            this.Uputs = new HashSet<Uput>();
            this.Uputs1 = new HashSet<Uput>();
            this.Uputs2 = new HashSet<Uput>();
            this.ZakazivanjePregledas = new HashSet<ZakazivanjePregleda>();
            this.ZakazivanjePregledas1 = new HashSet<ZakazivanjePregleda>();
        }

        public int ID { get; set; }
        [Required(ErrorMessage = "Polje je obavezno")]
        public string Ime { get; set; }
        [Required(ErrorMessage = "Polje je obavezno")]
        public string Prezime { get; set; }
        [Required(ErrorMessage = "Polje je obavezno")]
        [DisplayName("Broj zdravstvene knjižice")]
        [RegularExpression(@"^(\d{11})|([A-Za-z0-9]\w{7,})$", ErrorMessage = "Nije dobar format")]
        [Remote("ProveriBZK", "Pacijents", HttpMethod = "POST", ErrorMessage = "Postoji u bazi")]
        public string KorisnickoIme { get; set; }
        [Required(ErrorMessage = "Polje je obavezno")]
        [DataType(DataType.Password)]
        public string Lozinka { get; set; }
        [DisplayName("Datum rođenja")]
        public System.DateTime DatumRodjenja { get; set; }

        [NotMapped]
        public string ImePrezime
        {
            get
            {
                return Ime + " " + Prezime;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Izvestaj> Izvestajs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Izvestaj> Izvestajs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Karton> Kartons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Karton> Kartons1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uput> Uputs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uput> Uputs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uput> Uputs2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZakazivanjePregleda> ZakazivanjePregledas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZakazivanjePregleda> ZakazivanjePregledas1 { get; set; }
    }
}
