//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvidencijaPacijenata.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public abstract partial class Lekar : Korisnik
    {
        [DisplayName("Naziv odeljenja")]
        public int IDOdeljenja { get; set; }
        public string Licenca { get; set; }
        public string Slika { get; set; }
    
        public virtual Odeljenje Odeljenje { get; set; }
    }
}
