//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvidencijaPacijenata.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBZUstanovaEntities : DbContext
    {
        public DBZUstanovaEntities()
            : base("name=DBZUstanovaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Izvestaj> Izvestajs { get; set; }
        public virtual DbSet<Karton> Kartons { get; set; }
        public virtual DbSet<Korisnik> Korisniks { get; set; }
        public virtual DbSet<Odeljenje> Odeljenjes { get; set; }
        public virtual DbSet<RadnoVremeLekara> RadnoVremeLekaras { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Uput> Uputs { get; set; }
        public virtual DbSet<Ustanova> Ustanovas { get; set; }
        public virtual DbSet<Vesti> Vestis { get; set; }
        public virtual DbSet<ZakazivanjePregleda> ZakazivanjePregledas { get; set; }
    }
}
