//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvidencijaPacijenata.Models
{
    using System;
    using System.Linq;

    public partial class Pacijent : Korisnik
    {
        public string JMBG { get; set; }
        public string NosilacOsiguranja { get; set; }
        public string SrodstvoSaNosiocem { get; set; }
        public Nullable<int> IDOdeljenja { get; set; }
        public Nullable<int> IDUstanove { get; set; }
        public string KrvnaGrupa { get; set; }
        public string Pol { get; set; }
        public string Adresa { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public System.DateTime IstekOsiguranja { get; set; }
        public int Odobren { get; set; }

        public virtual Odeljenje Odeljenje { get; set; }
        public virtual Ustanova Ustanova { get; set; }

        public Pacijent() { }
        public Pacijent(string KorisnickoIme, string Lozinka)
        {
            DateTime dt = DateTime.Now;
            DateTime dateOnly = dt.Date;
            using (DBZUstanovaEntities model = new DBZUstanovaEntities())
            {
            }
        }
    }
}
